### ISSUE TITLE
Application Error - Crashing

### ISSUE THREAD

**Issue by UglyDreams** [IntelSDM/RustDmaCheat#2] opened 2023-12-22 02:04 UTC
All features are working as expected, however RustClient.exe will eventually crash. It could be as quick as 10 minutes, or as long as an hour. Here is the application error from Event Viewer:

Faulting application name: RustClient.exe, version: 2021.3.24.4316, time stamp: 0x643f9544
Faulting module name: GameAssembly.dll, version: 0.0.0.0, time stamp: 0x65816aeb
Exception code: 0xc0000005
Fault offset: 0x0000000000769e9d
Faulting process id: 0x5228
Faulting application start time: 0x01da3465c0a5869f
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Rust\RustClient.exe
Faulting module path: C:\Program Files (x86)\Steam\steamapps\common\Rust\GameAssembly.dll
Report Id: 7b4ed086-e9f2-41dc-b37e-16f06f44a10e

Here is the current state of each feature:

bool SpiderMan = false;
bool NoRecoil = true;
int RecoilReduction = 15;
bool AdminFlag = false;
bool ChangeFov = false;
int Fov = 100;
bool ChangeTime = false;
int Time = 12;
bool BrightNight = false;
bool BrightCaves = false;
bool AdminEsp = true;

**Comment by IntelSDM** [comment] 2023-12-22 17:16
Thank you for the comprehensive bug report. I don't tend to keep it loaded for too long but one of my friends said he has the same issue. It's either the DTB fix or more likely since the issue is coming from the gameassembly.dll; no recoil. I am going to take a wild guess and say that the address for baseprojectile isn't consistent or something along those lines of an address becoming invalid or on some items, the baseprojectile address leads to some other class and all the other checks somehow pass on that one item and when it writes to that address the game crashes. That's purely guess work though. 
I will look into it but right now I am trying to figure out why my websockets are acting up on my remote pc overlay.

**Comment by UglyDreams** [comment] 2023-12-23 03:46
> Thank you for the comprehensive bug report. I don't tend to keep it loaded for too long but one of my friends said he has the same issue. It's either the DTB fix or more likely since the issue is coming from the gameassembly.dll; no recoil. I am going to take a wild guess and say that the address for baseprojectile isn't consistent or something along those lines of an address becoming invalid or on some items, the baseprojectile address leads to some other class and all the other checks somehow pass on that one item and when it writes to that address the game crashes. That's purely guess work though. I will look into it but right now I am trying to figure out why my websockets are acting up on my remote pc overlay.

I disabled NoRecoil and was able to play without any issues.

**Comment by IntelSDM** [comment] 2023-12-24 10:58
Thanks for the extended testing. I assume that I need to add some more checks for baseprojectile then.

**Comment by UglyDreams** [comment] 2024-01-03 01:43
Completely unrelated- Are you planning on releasing a public DMA cheat for EFT?

**Comment by IntelSDM** [comment] 2024-01-03 09:30
> Are you planning on releasing a public DMA cheat for EFT? This source has helped me quite a bit with developing my own Rust app and would like to see something similar with EFT.

Personally, I hate EFT stuff, I merely maintain my internal for it.  I keep my public EFT repos rather hard to find because I don't exactly want DMCAs from Battlestate Games. If you want to make a DMA EFT cheat then there are a few sources on GitHub:
https://github.com/bytemyass/EFTLeecher
https://github.com/danielignacak/RadarBase

**Comment by IntelSDM** [comment] 2024-01-10 22:29
Fixed in the latest version. No more crashing from recoil.

**Closed by IntelSDM** 2024-01-10 22:29 UTC
Labels: bug
